// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hhwfkeuolfpawzkijuaw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhod2ZrZXVvbGZwYXd6a2lqdWF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzQxMjUsImV4cCI6MjA2NzYxMDEyNX0.SXIj45ZGNquj0klbac9cvNUWkl0UQ6aSbgTswiX21xk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});